### ISSUE TITLE
Rayon github linkが誰かがフォークした本家じゃないやつになってる

### ISSUE THREAD

**Issue by t-hishinuma** [termoshtt/zenn-content#42]
Rayonクレートのリンクが
https://github.com/nikomatsakis/rayon
になってますが，これForkされたやつで正しい本家は
https://github.com/rayon-rs/rayon
じゃないでしょうか．

まぁすぐFork元に飛べるから気にならないんだけど気付いたので報告しておきます

**Comment by t-hishinuma** [comment]
あ，ここの最初ね

https://zenn.dev/termoshtt/books/b4bce1b9ea5e6853cb07/viewer/rayon

**Comment by termoshtt** [comment]
これは元々の作者のリポジトリですね(多分rayon-rs以下に移った後個人用のリポジトリを何か試すためにフォークしたんでしょう)

Fixed in https://github.com/termoshtt/zenn-content/commit/87487472fd2bd979843289b57b9190e5d86464f8
