### ISSUE TITLE
Rust Slack→Zulip (Rustで数値計算)

### ISSUE THREAD

**Issue by ultimatile** [termoshtt/zenn-content#44]
https://github.com/termoshtt/zenn-content/blob/4a33b25a9a57c3a30dd3b02269836446ee89b21d/books/b4bce1b9ea5e6853cb07/intro.md?plain=1#L20

Rust日本語Slackの方に参加していないのでそちらの様子はわかりませんが, メインのコミュニティがZulipに移行しているのならば, こちらのリンクはZulipにしておいた方が良いのではないでしょうか?

**Comment by termoshtt** [comment]
その通りですね、修正します
